// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiEK1aRpKUDAYZ-KBwVe4aP6Lwn13MgUg',
    appId: '1:426334946374:web:c67022f97b57a4e6be7647',
    messagingSenderId: '426334946374',
    projectId: 'multimediamoviles',
    authDomain: 'multimediamoviles.firebaseapp.com',
    databaseURL: 'https://multimediamoviles-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'multimediamoviles.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0rQUp1AFP13RZu5JYjc8-XHAOXw-qyk0',
    appId: '1:426334946374:android:316a93ca6e649004be7647',
    messagingSenderId: '426334946374',
    projectId: 'multimediamoviles',
    databaseURL: 'https://multimediamoviles-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'multimediamoviles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFjZmWyIp0UeZksnJQJTEcJxEt354W90',
    appId: '1:426334946374:ios:0caef62c2ff95885be7647',
    messagingSenderId: '426334946374',
    projectId: 'multimediamoviles',
    databaseURL: 'https://multimediamoviles-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'multimediamoviles.appspot.com',
    iosBundleId: 'com.example.loginAlternativo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFjZmWyIp0UeZksnJQJTEcJxEt354W90',
    appId: '1:426334946374:ios:8da2783fd82ba48cbe7647',
    messagingSenderId: '426334946374',
    projectId: 'multimediamoviles',
    databaseURL: 'https://multimediamoviles-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'multimediamoviles.appspot.com',
    iosBundleId: 'com.example.loginAlternativo.RunnerTests',
  );
}
